import Nav from '@/components/Nav'
import Footer from '@/components/Footer'

export const metadata = {
  title: 'Terms of Service — Roovero',
}

const sections = [
  {
    id: '01',
    heading: 'About the Service',
    content: (
      <p>
        Sampreeth Singh Wadhwa, operating as Roovero ("we", "us", "our"), provides an AI-assisted social
        media content management platform — including content calendar generation, in-app approval
        flows, image and video production, Meta publishing, and analytics — accessible through the
        Roovero mobile application and website at roovero.com. These Terms govern your access to
        and use of the Service. By creating an account, you agree to be bound by them.
      </p>
    ),
  },
  {
    id: '02',
    heading: 'Eligibility',
    content: (
      <p>
        You must be at least 18 years old to use the Service. By registering, you confirm that the
        information you provide is accurate and that you have authority to connect any social media
        accounts through the Service.
      </p>
    ),
  },
  {
    id: '03',
    heading: 'Accounts',
    content: (
      <p>
        You are responsible for maintaining the security of your account credentials. Notify us
        immediately at{' '}
        <a href="mailto:hello@roovero.com" className="text-ink underline hover:text-amber transition-colors">
          hello@roovero.com
        </a>{' '}
        if you suspect unauthorised access. We are not liable for losses resulting from compromised
        credentials.
      </p>
    ),
  },
  {
    id: '04',
    heading: 'Subscriptions and billing',
    content: (
      <>
        <ul className="space-y-4">
          <li>
            <span className="font-medium text-ink">Plans.</span>{' '}
            Roovero offers a Free plan and four paid plans — Starter, Core, Growth, and Studio.
            Features and usage limits per plan are described in the app and at roovero.com/pricing.
          </li>
          <li>
            <span className="font-medium text-ink">Pricing.</span>{' '}
            All prices are listed in Indian Rupees (INR) and are GST-inclusive. The GST portion is
            disclosed separately at checkout and on billing confirmations.
          </li>
          <li>
            <span className="font-medium text-ink">Billing cycle.</span>{' '}
            Paid subscriptions are billed monthly through Razorpay. Your payment method is charged
            at the start of each billing period.
          </li>
          <li>
            <span className="font-medium text-ink">Add-ons.</span>{' '}
            Additional credits — reels, carousels, image edits, brand photos, AI replies — may be
            purchased as monthly recurring add-ons or as one-time purchases.
          </li>
          <li>
            <span className="font-medium text-ink">Plan changes.</span>{' '}
            Upgrades take effect immediately. Downgrades take effect at the next billing period.
          </li>
        </ul>
      </>
    ),
  },
  {
    id: '05',
    heading: 'Cancellation',
    content: (
      <p>
        You may cancel your subscription at any time from within the Roovero app. Cancellation stops
        future billing immediately. Your plan and associated features remain active until the end of
        the current paid billing period. We do not issue pro-rated refunds for unused days in a
        billing period — see our{' '}
        <a href="/refund" className="text-ink underline hover:text-amber transition-colors">
          Refund Policy
        </a>{' '}
        for details.
      </p>
    ),
  },
  {
    id: '06',
    heading: 'Content and intellectual property',
    content: (
      <>
        <ul className="space-y-4">
          <li>
            <span className="font-medium text-ink">Your content.</span>{' '}
            You retain ownership of your business information, brand assets, and any content you
            provide to the Service.
          </li>
          <li>
            <span className="font-medium text-ink">Generated content.</span>{' '}
            Content generated by Roovero on your behalf — captions, images, reels, carousels — is
            provided for your use and publication. You are responsible for reviewing and approving
            all content before it is published.
          </li>
          <li>
            <span className="font-medium text-ink">Roovero IP.</span>{' '}
            The Service, its software, design, and underlying systems are the property of
            Sampreeth Singh Wadhwa. You may not copy, reverse-engineer, or redistribute any part
            of the Service.
          </li>
        </ul>
      </>
    ),
  },
  {
    id: '07',
    heading: 'Meta and Instagram integration',
    content: (
      <p>
        Use of Instagram publishing through Roovero is subject to Meta's Terms of Service and
        Community Standards. You are solely responsible for ensuring that content you approve and
        publish complies with Meta's policies. Roovero is not responsible for content removals,
        account restrictions, or enforcement actions taken by Meta.
      </p>
    ),
  },
  {
    id: '08',
    heading: 'Acceptable use',
    content: (
      <>
        <p className="mb-4">You agree not to use the Service to:</p>
        <ul className="space-y-2">
          {[
            'Publish spam, misleading content, or content that violates applicable law',
            'Impersonate any person, business, or entity',
            'Circumvent usage limits or platform safeguards',
            "Interfere with the operation of the Service or other users' accounts",
          ].map((item) => (
            <li key={item} className="flex items-start gap-2.5">
              <span className="text-amber mt-0.5 flex-shrink-0">–</span>
              {item}
            </li>
          ))}
        </ul>
        <p className="mt-4">
          We reserve the right to suspend or terminate accounts that violate these terms, with or
          without notice.
        </p>
      </>
    ),
  },
  {
    id: '09',
    heading: 'Service availability',
    content: (
      <p>
        We aim to keep Roovero operational and available, but we do not guarantee uninterrupted
        access. Maintenance windows, infrastructure issues, or third-party service disruptions
        (Razorpay, Meta, Firebase) may affect availability. We will communicate planned downtime
        where reasonably possible.
      </p>
    ),
  },
  {
    id: '10',
    heading: 'Limitation of liability',
    content: (
      <p>
        To the maximum extent permitted by applicable Indian law, Roovero shall not be liable for
        indirect, incidental, consequential, or punitive damages arising from your use of the
        Service. Our total liability for any claim shall not exceed the amount you paid us in the
        three calendar months immediately preceding the claim.
      </p>
    ),
  },
  {
    id: '11',
    heading: 'Changes to these terms',
    content: (
      <p>
        We may update these Terms periodically. Material changes will be communicated via email or
        in-app notice at least 7 days before they take effect. Continued use of the Service after
        the effective date constitutes acceptance of the revised terms.
      </p>
    ),
  },
  {
    id: '12',
    heading: 'Governing law',
    content: (
      <p>
        These Terms are governed by the laws of India. Any dispute arising from or relating to these
        Terms or the Service shall be subject to the exclusive jurisdiction of courts in Bengaluru,
        Karnataka.
      </p>
    ),
  },
  {
    id: '13',
    heading: 'Contact',
    content: (
      <p>
        For questions about these Terms, write to:{' '}
        <a href="mailto:hello@roovero.com" className="text-ink underline hover:text-amber transition-colors">
          hello@roovero.com
        </a>
        .
      </p>
    ),
  },
]

export default function TermsPage() {
  return (
    <>
      <Nav />
      <main className="pt-16">
        <section className="bg-white py-24 px-6">
          <div className="max-w-narrow mx-auto">
            <div className="flex items-center gap-3 mb-8">
              <span className="w-8 h-px bg-amber" />
              <span className="text-xs tracking-widest text-smoke uppercase font-sans">Legal</span>
            </div>
            <h1
              className="font-serif italic text-ink mb-4"
              style={{ fontSize: 'clamp(2rem, 4vw, 3rem)', letterSpacing: '-0.025em' }}
            >
              Terms of Service
            </h1>
            <p className="text-sm text-smoke font-sans mb-16">
              Effective date: 1 May 2026 &nbsp;·&nbsp; Last updated: 1 May 2026
            </p>

            <div className="space-y-12">
              {sections.map((section) => (
                <div key={section.id} className="border-t border-mist pt-10">
                  <div className="flex items-baseline gap-4 mb-5">
                    <span className="text-xs text-amber font-sans tabular-nums">{section.id}</span>
                    <h2 className="font-serif italic text-ink text-xl">{section.heading}</h2>
                  </div>
                  <div className="text-smoke font-sans text-sm leading-relaxed pl-8">
                    {section.content}
                  </div>
                </div>
              ))}
            </div>

            <div className="mt-16 pt-10 border-t border-mist">
              <p className="text-xs text-ash font-sans">
                Sampreeth Singh Wadhwa · Bengaluru, India ·{' '}
                <a href="mailto:hello@roovero.com" className="hover:text-smoke transition-colors">
                  hello@roovero.com
                </a>
              </p>
            </div>
          </div>
        </section>
      </main>
      <Footer />
    </>
  )
}
